version: '3.5'

services:
  nginx:
    image: nginx:1.25.3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api01
      - api02
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"
  api01: &api
    # Lembre-se de que seu serviço HTTP deve estar hospedado num repositório
    # publicamente acessível! Ex.: hub.docker.com
    image: vineboneto/rinha-backend-q1:latest
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api01
    environment:
      - DB_HOSTNAME=db
    ports:
      - 8081:3000
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100MB"
  api02:
    <<: *api 
    hostname: api02
    ports:
      - 8082:3000
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "300MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
