version: '3.5'

services:
  nginx:
    image: nginx:1.25.3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - 9999:9999
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"
  api01: &api
    network_mode: host
    # Lembre-se de que seu serviço HTTP deve estar hospedado num repositório
    # publicamente acessível! Ex.: hub.docker.com
    image: vineboneto/rinha-backend-q1:latest
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api01
    environment:
      - DB_HOSTNAME=localhost
      - PORT=8081
    ports:
      - 8081:8081
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "150MB"
  api02:
    <<: *api 
    hostname: api02
    environment:
      - DB_HOSTNAME=localhost
      - PORT=8082
    ports:
      - 8082:8082
  db:
    network_mode: host
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rinha
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "150MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
