@api_url=http://localhost:3000

### Extrato
GET {{api_url}}/clientes/10/extrato HTTP/1.1
content-type: application/json

### Transação
POST {{api_url}}/clientes/1/transacoes HTTP/1.1
content-type: application/json

{
  "valor": 1,
  "tipo": "d",
  "descricao": "Pag. luz"
}